console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'FileBasedFindingsReport'

output-reports:
  active: true
  exclude:
    - 'TxtOutputReport'
    - 'XmlOutputReport'

comments:
  active: true

complexity:
  active: true
  LongMethod:
    active: true
    ignoreAnnotated:
      - 'Preview'
      - 'PreviewLightDark'
      - 'Composable'
  LongParameterList:
    active: true
    ignoreAnnotated:
      - 'Preview'
      - 'PreviewLightDark'
      - 'Composable'
  TooManyFunctions:
    active: true
    thresholdInFiles: 40
    thresholdInClasses: 18
    thresholdInInterfaces: 10
    thresholdInObjects: 20
    thresholdInEnums: 5

coroutines:
  active: true
  InjectDispatcher:
    active: true
    dispatcherNames: ['IO', 'Default', 'Unconfined']
  SleepInsteadOfDelay:
    active: true
  SuspendFunWithFlowReturnType:
    active: true
  GlobalCoroutineUsage:
    active: true

empty-blocks:
  active: true

exceptions:
  active: true

formatting:
  active: true
  android: true
  ImportOrdering:
    active: true
    autoCorrect: true
  MaximumLineLength:
    active: true
    maxLineLength: 120
    excludes:
      - "**/test/**"
      - "**/androidTest/**"
      - "**/testFixtures/**"
      - "**/roboletricTest/**"
  Filename:
    active: true
  PackageName:
    active: true

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - 'Preview'
      - 'PreviewLightDark'
      - 'Composable'

performance:
  active: true

potential-bugs:
  active: true
  UnconditionalJumpStatementInLoop:
    active: true
  NullCheckOnMutableProperty:
    active: true

style:
  active: true
  UnusedParameter:
    active: true
  UnusedPrivateProperty:
    active: true
  ForbiddenImport:
    active: true
    imports: []
    forbiddenPatterns: ''
  ForbiddenComment:
    active: true
    comments:
      - reason: 'Forbidden FIXME todo marker in comment, please fix the problem.'
        value: 'FIXME:'
      - reason: 'Forbidden STOPSHIP todo marker in comment, please address the problem before shipping the code.'
        value: 'STOPSHIP:'
    allowedPatterns: ''
  MaxLineLength:
    active: true
    maxLineLength: 120
    excludeCommentStatements: true
    excludes:
      - "**/test/**"
      - "**/androidTest/**"
      - "**/testFixtures/**"
      - "**/roboletricTest/**"
  UnnecessaryAbstractClass:
    active: true
    ignoreAnnotated:
      - Module
  MagicNumber:
    active: true
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**', '**/*.kts' ]
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '0.2'
      - '1024'
    ignoreNamedArgument: true
    ignoreEnums: true
    ignorePropertyDeclaration: true
    ignoreLocalVariableDeclaration: true
    ignoreExtensionFunctions: true
    ignoreAnnotated:
      - 'androidx.compose.runtime.Composable'
  UnusedPrivateMember:
    active: true
    ignoreAnnotated:
      - 'Preview'
      - 'PreviewLightDark'
  ReturnCount:
    active: true

Compose:
  ComposableAnnotationNaming:
    active: true
  ComposableNaming:
    active: true
  ComposableParamOrder:
    active: true
  CompositionLocalAllowlist:
    active: false
  CompositionLocalNaming:
    active: true
  ContentEmitterReturningValues:
    active: true
  ContentTrailingLambda:
    active: true
  ContentSlotReused:
    active: true
  DefaultsVisibility:
    active: true
  LambdaParameterEventTrailing:
    active: true
  LambdaParameterInRestartableEffect:
    active: true
  Material2:
    active: true
  ModifierClickableOrder:
    active: true
  ModifierComposed:
    active: true
  ModifierMissing:
    active: true
  ModifierNaming:
    active: true
  ModifierNotUsedAtRoot:
    active: true
  ModifierReused:
    active: true
  ModifierWithoutDefault:
    active: true
  MultipleEmitters:
    active: true
  MutableParams:
    active: true
  MutableStateAutoboxing:
    active: true
  MutableStateParam:
    active: true
  ParameterNaming:
    active: true
  PreviewAnnotationNaming:
    active: true
  PreviewNaming:
    active: false
  PreviewPublic:
    active: true
  RememberMissing:
    active: true
  RememberContentMissing:
    active: true
  UnstableCollections:
    active: true
  ViewModelForwarding:
    active: true
  ViewModelInjection:
    active: true