console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'FileBasedFindingsReport'

output-reports:
  active: true
  exclude:
    - 'TxtOutputReport'
    - 'XmlOutputReport'

comments:
  active: false

complexity:
  active: false

coroutines:
  active: false

empty-blocks:
  active: false

exceptions:
  active: false

formatting:
  active: true
  android: true
  ImportOrdering:
    active: false
    autoCorrect: false
  MaximumLineLength:
    active: true
    maxLineLength: 120
    excludes:
      - "**/test/**"
      - "**/androidTest/**"
      - "**/testFixtures/**"
      - "**/roboletricTest/**"
  Filename:
    active: false
  PackageName:
    active: false

naming:
  active: false

performance:
  active: false

potential-bugs:
  active: false

style:
  active: true
  UnusedParameter:
    active: false
  UnusedPrivateProperty:
    active: false
  ForbiddenImport:
    active: false
    imports: [ ]
    forbiddenPatterns: '(ktor.*|koin.*|kotlinx.datetime.*)'
  ForbiddenComment:
    active: true
    comments:
      - reason: 'Forbidden FIXME todo marker in comment, please fix the problem.'
        value: 'FIXME:'
      - reason: 'Forbidden STOPSHIP todo marker in comment, please address the problem before shipping the code.'
        value: 'STOPSHIP:'
    allowedPatterns: ''
  MaxLineLength:
    active: true
    maxLineLength: 120
    excludeCommentStatements: true
    excludes:
      - "**/test/**"
      - "**/androidTest/**"
      - "**/testFixtures/**"
      - "**/roboletricTest/**"
  UnnecessaryAbstractClass:
    active: true
    ignoreAnnotated:
      - Module
  MagicNumber:
    active: false
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**', '**/*.kts' ]
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '0.2'
      - '1024'
  UnusedPrivateMember:
    active: true
    ignoreAnnotated:
      - 'Preview'
  ReturnCount:
    active: false

Compose:
  ComposableAnnotationNaming:
    active: true
  ComposableNaming:
    active: true
  ComposableParamOrder:
    active: true
  CompositionLocalAllowlist:
    active: false
  CompositionLocalNaming:
    active: true
  ContentEmitterReturningValues:
    active: true
  ContentTrailingLambda:
    active: true
  ContentSlotReused:
    active: true
  DefaultsVisibility:
    active: true
  LambdaParameterEventTrailing:
    active: true
  LambdaParameterInRestartableEffect:
    active: true
  Material2:
    active: true
  ModifierClickableOrder:
    active: true
  ModifierComposed:
    active: true
  ModifierMissing:
    active: true
  ModifierNaming:
    active: true
  ModifierNotUsedAtRoot:
    active: true
  ModifierReused:
    active: true
  ModifierWithoutDefault:
    active: true
  MultipleEmitters:
    active: true
  MutableParams:
    active: true
  MutableStateAutoboxing:
    active: true
  MutableStateParam:
    active: true
  ParameterNaming:
    active: true
  PreviewAnnotationNaming:
    active: true
  PreviewNaming:
    active: false
  PreviewPublic:
    active: true
  RememberMissing:
    active: true
  RememberContentMissing:
    active: true
  UnstableCollections:
    active: true
  ViewModelForwarding:
    active: false
  ViewModelInjection:
    active: true
