name: Assign Reviewer on Dependabot PR

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main
    paths:
      - '**'

jobs:
  assign-reviewer:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Assign Joseph Sanjaya as reviewer
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.request('POST /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers', {
              reviewers: ['JosephSanjaya']
            })
